-- EC2 SAFE E2T Live Data Import
-- Note: Does NOT truncate existing tables so your existing 2-3 important clients stay intact.
-- Removes only obvious dummy test records:
DELETE FROM machines WHERE client_name LIKE '%Test Client%' OR client_name LIKE '%Dummy%';
DELETE FROM clients WHERE client_name LIKE '%Test Client%' OR client_name LIKE '%Dummy%';

-- 1. Insert or update Clients from Excel
INSERT INTO `clients` (`client_name`, `contact_person`, `contact_mobile`, `client_phone`, `client_address`, `client_state`, `client_city`, `client_type`, `password`) VALUES ('E2T Enterprise Client', '9124522812', 'Pattamunda', 'Pattamundai Nea', 'AT_2122_PI0032_1', 'India', 'E2T-MDL1-Free', 'Govt', '123456') ON DUPLICATE KEY UPDATE contact_person = VALUES(contact_person), client_address = VALUES(client_address);

-- 2. Insert Projects from Excel
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 1', 'E2T Enterprise Client', '1', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 2', 'E2T Enterprise Client', '2', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 3', 'E2T Enterprise Client', '3', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 5', 'E2T Enterprise Client', '5', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 6', 'E2T Enterprise Client', '6', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 7', 'E2T Enterprise Client', '7', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 8', 'E2T Enterprise Client', '8', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 9', 'E2T Enterprise Client', '9', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 10', 'E2T Enterprise Client', '10', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 11', 'E2T Enterprise Client', '11', 'Ongoing', NOW());
INSERT INTO `projects` (`project_name`, `client_name`, `work_ord_no`, `project_status`, `created`) VALUES ('Project 12', 'E2T Enterprise Client', '12', 'Ongoing', NOW());

-- 3. Insert or update Machines from Excel
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1001', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_1', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1002', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_2', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1003', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_3', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1004', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_4', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1005', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_5', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1006', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_6', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1007', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_7', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1008', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_8', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1009', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_9', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1010', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_10', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1011', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_11', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1012', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_12', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1013', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_13', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1014', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_14', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1015', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_15', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1016', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_16', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1017', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_17', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1018', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_18', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1019', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_19', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1020', 'Housing and Urban Develop', 'E2T Enterprise Client', 'Project 1', 'E2T-MDL1-Free', 'AT_2122_PI0032_20', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1021', 'Vikasnagar Kusumpti, Bloc', 'E2T Enterprise Client', 'Project 2', 'E2T-MDL1-Free', 'AT2223SO01_E2T1', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1022', 'Vikasnagar Kusumpti, Bloc', 'E2T Enterprise Client', 'Project 2', 'E2T-MDL1-Coin2Rs', 'AT2223SO01_E2T2', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1023', 'Udupi Panchayat Office, k', 'E2T Enterprise Client', 'Project 3', 'E2T-MDL1-Coin1Rs', 'AT2223SO10_E2T31', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1024', 'Udupi Panchayat Office, k', 'E2T Enterprise Client', 'Project 3', 'E2T-MDL1-Coin1Rs', 'AT2223SO10_E2T32', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1025', 'Udupi Panchayat Office, k', 'E2T Enterprise Client', 'Project 3', 'E2T-MDL1-Coin1Rs', 'AT2223SO10_E2T33', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1026', 'Udupi Panchayat Office, k', 'E2T Enterprise Client', 'Project 3', 'E2T-MDL1-Coin1Rs', 'AT2223SO10_E2T34', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1027', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T35', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1028', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T36', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1029', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T37', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1030', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T38', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1031', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T39', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1032', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T40', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1033', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T41', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1034', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T42', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1035', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T43', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1036', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T44', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1037', 'Savani Heritage Conservat', 'E2T Enterprise Client', 'Project 5', 'E2T-MDL1-Free', 'AT2223SO0010_E2T45', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1038', 'Kagal Nagar Parishad Kolh', 'E2T Enterprise Client', 'Project 6', 'E2T-MDL3-Coin1Rs', 'AI2324SO0002_E2T46', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1039', 'Kagal Nagar Parishad Kolh', 'E2T Enterprise Client', 'Project 6', 'E2T-MDL3-Coin1Rs', 'AI2324SO0002_E2T47', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1040', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO0002_E2T15', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1041', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T16_RM2', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1042', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T17_RM3', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1043', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T18_RM4', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1044', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T19_RF5', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1045', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T20_RF6', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1046', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T21_RF7', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1047', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T22_RF8', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1048', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T23_LM9', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1049', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T24_LM10', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1050', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T25_LM11', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1051', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T26_LM12', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1052', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T27_LF13', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1053', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T28_LF14', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1054', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T29_LF15', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1055', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T30_LF16', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1056', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T31_RD17', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1057', 'Shri Trimbakeshwar Dewast', 'E2T Enterprise Client', 'Project 7', 'E2T-MDL1-Free', 'AT2223SO2_E2T32_LD18', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1058', 'Shree Saptashrungi Nivasa', 'E2T Enterprise Client', 'Project 8', 'E2T-MDL3-Coin5Rs', 'AT2324SO8_E2T61', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1059', 'Shree Saptashrungi Nivasa', 'E2T Enterprise Client', 'Project 8', 'E2T-MDL3-Coin5Rs', 'AT2324SO8_E2T62', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1060', 'Shree Saptashrungi Nivasa', 'E2T Enterprise Client', 'Project 8', 'E2T-MDL3-Coin5Rs', 'AT2324SO8_E2T63', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1061', 'Shree Saptashrungi Nivasa', 'E2T Enterprise Client', 'Project 8', 'E2T-MDL3-Coin5Rs', 'AT2324SO8_E2T64', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1062', 'Nagar Palika Santrampur,P', 'E2T Enterprise Client', 'Project 9', 'E2T-MDL3-Coin5Rs', 'AI2324SO8_E2T65', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1063', 'Nagar Palika Santrampur,P', 'E2T Enterprise Client', 'Project 9', 'E2T-MDL3-Coin5Rs', 'AI2324SO8_E2T66', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1064', 'Jintur Municiple Council,', 'E2T Enterprise Client', 'Project 10', 'E2T-MDL3-Coin5Rs', 'AI2324SO20_E2T67', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1065', 'Jintur Municiple Council,', 'E2T Enterprise Client', 'Project 10', 'E2T-MDL3-Coin5Rs', 'AI2324SO20_E2T68', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1066', 'Jintur Municiple Council,', 'E2T Enterprise Client', 'Project 10', 'E2T-MDL3-Coin5Rs', 'AI2324SO20_E2T69', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1067', 'Airports Authority of Ind', 'E2T Enterprise Client', 'Project 11', 'E2T-MDL2 - Tokan Operated', 'AT2324SO13_E2T70', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1068', 'Airports Authority of Ind', 'E2T Enterprise Client', 'Project 11', 'E2T-MDL2 - Tokan Operated', 'AT2324SO13_E2T71', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1069', 'Airports Authority of Ind', 'E2T Enterprise Client', 'Project 11', 'E2T-MDL2 - Tokan Operated', 'AT2324SO13_E2T72', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1070', 'Airports Authority of Ind', 'E2T Enterprise Client', 'Project 11', 'E2T-MDL2 - Tokan Operated', 'AT2324SO13_E2T73', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
INSERT INTO `machines` (`machine_id`, `machine_code`, `client_name`, `project_name`, `inst_address`, `address`, `mode`, `free`, `coin`, `upi`, `digital_token`, `uses_amt`, `status`) VALUES ('MCH-1071', 'Vaibhavwadi GrampanchaytO', 'E2T Enterprise Client', 'Project 12', 'E2T-MDL3-Coin5Rs', 'AT2223SO2_E2T33_', 'Coin', 'no', 'no', 'no', 'no', 5, 'active') ON DUPLICATE KEY UPDATE client_name = VALUES(client_name), uses_amt = VALUES(uses_amt), mode = VALUES(mode), free = VALUES(free), coin = VALUES(coin), upi = VALUES(upi);
