import React from "react";

const PrintTemplate = ({ 
  title, 
  children, 
  isTable = true,
  clientName,
  toiletId,
  location,
  clientLogo
}) => {
  const currentDate = new Date();
  const dateStr = currentDate.toLocaleDateString();
  const timeStr = currentDate.toLocaleTimeString();
  const reportId = `RPT-${Math.floor(Math.random() * 100000000)}`;

  const Header = () => (
    <div className="print-header-content" style={{ display: 'flex', flexDirection: 'column', width: '100%', marginBottom: '15px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px', width: '100%' }}>
        {/* Left Side: Client Logo */}
        <div style={{ width: '150px', display: 'flex', alignItems: 'center', justifyContent: 'flex-start' }}>
          {clientLogo ? (
            <img src={clientLogo} alt="Client Logo" style={{ maxHeight: '60px', maxWidth: '140px', objectFit: 'contain' }} />
          ) : (
            <div style={{ border: '1.5px solid #2563eb', padding: '8px 14px', color: '#64748b', fontSize: '11px', fontWeight: 'bold', borderRadius: '4px', textAlign: 'center' }}>
              Client Logo
            </div>
          )}
        </div>

        {/* Center: Title & Details exactly matching HD PDF */}
        <div style={{ textAlign: 'center', flexGrow: 1, padding: '0 10px' }}>
          <h2 style={{ margin: '0 0 6px 0', color: '#10b981', fontSize: '18pt', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            {title}
          </h2>
          {clientName && (
            <div style={{ color: '#2563eb', fontSize: '11pt', fontWeight: '700', marginBottom: '4px' }}>
              Client Name: {clientName}
            </div>
          )}
          {toiletId && (
            <div style={{ color: '#64748b', fontSize: '10pt', fontWeight: '500', marginBottom: '2px' }}>
              Toilet ID: {toiletId}
            </div>
          )}
          {location && (
            <div style={{ color: '#64748b', fontSize: '10pt', fontWeight: '500', marginBottom: '4px' }}>
              Location: {location}
            </div>
          )}
          <div style={{ fontSize: '8pt', color: '#888', marginTop: '4px' }}>
            Report ID: {reportId} &nbsp;|&nbsp; Date: {dateStr}, {timeStr}
          </div>
        </div>

        {/* Right Side: SmartBuddy HD Logo */}
        <div style={{ width: '150px', display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
          <img src="/SB_Logo.jpg" alt="SmartBuddy Logo" style={{ maxHeight: '60px', maxWidth: '140px', objectFit: 'contain' }} />
        </div>
      </div>
      <div style={{ borderBottom: '2px solid #2563eb' }}></div>
    </div>
  );

  const Footer = () => (
    <div className="print-footer-content" style={{ width: '100%', marginTop: '30px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '150px', borderTop: '1px solid #94a3b8', marginBottom: '5px' }}></div>
          <span style={{ fontSize: '11px', fontWeight: 'bold', color: '#475569' }}>System Administrator</span>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '150px', borderTop: '1px solid #94a3b8', marginBottom: '5px' }}></div>
          <span style={{ fontSize: '11px', fontWeight: 'bold', color: '#475569' }}>Authorized Signatory</span>
        </div>
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '9px', color: '#64748b', borderTop: '1px solid #e2e8f0', paddingTop: '5px' }}>
        <div>
          AARYA INNOVTECH PVT. LTD. CIN: U29305MH2019PTC327551 | +91 8806796868<br/>
          Nashik Office: Flat No. 4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.
        </div>
        <div style={{ textAlign: 'right' }}>
          Generated by System
        </div>
      </div>
    </div>
  );

  return (
    <div className="print-template-wrapper">
      <img className="print-only" src="/SB_Logo.jpg" alt="Watermark" style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '450px', opacity: 0.05, zIndex: -1, pointerEvents: 'none' }} />
      
      {isTable ? (
        <table className="print-layout-table" style={{ width: '100%', borderCollapse: 'collapse', border: 'none' }}>
          <thead className="print-only">
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <Header />
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <div className="print-body-content">
                  {children}
                </div>
              </td>
            </tr>
          </tbody>
          <tfoot className="print-only">
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <Footer />
              </td>
            </tr>
          </tfoot>
        </table>
      ) : (
        <div style={{ width: '100%' }}>
          <div className="print-only"><Header /></div>
          <div className="print-body-content">
            {children}
          </div>
          <div className="print-only"><Footer /></div>
        </div>
      )}
    </div>
  );
};

export default PrintTemplate;
