import React from "react";
const logo = "/smartbuddy.png";

const PrintTemplate = ({ title, children, isTable = true }) => {
  const currentDate = new Date();
  const dateStr = currentDate.toLocaleDateString();
  const timeStr = currentDate.toLocaleTimeString();
  const reportId = `RPT-${Math.floor(Math.random() * 100000000)}`;

  const Header = () => (
    <div className="print-header-content" style={{ display: 'flex', flexDirection: 'column', width: '100%', marginBottom: '15px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
        <img src={logo} alt="Logo" style={{ height: '70px', objectFit: 'contain' }} />
        <div style={{ textAlign: 'center', flexGrow: 1 }}>
          <h2 style={{ margin: 0, color: '#10b981', fontSize: '18px', fontWeight: 'bold' }}>
            ELECTRONIC ECO TOILET <span style={{ color: '#2563eb' }}>MONITORING SYSTEM</span>
          </h2>
          <h3 style={{ margin: '5px 0', color: '#2563eb', fontSize: '14px', fontWeight: 'bold' }}>{title}</h3>
          <p style={{ margin: 0, fontSize: '10px', color: '#555' }}>
            Report ID: {reportId} &nbsp;&nbsp;|&nbsp;&nbsp; Date: {dateStr}, {timeStr} &nbsp;&nbsp;|&nbsp;&nbsp; Generated By: System User
          </p>
        </div>
        <div style={{ width: '70px' }}></div> {/* Spacer for centering */}
      </div>
      <div style={{ borderBottom: '2px solid #2563eb' }}></div>
    </div>
  );

  const Footer = () => (
    <div className="print-footer-content" style={{ width: '100%', marginTop: '30px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '150px', borderTop: '1px solid #94a3b8', marginBottom: '5px' }}></div>
          <span style={{ fontSize: '11px', fontWeight: 'bold', color: '#475569' }}>System Administrator</span>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '150px', borderTop: '1px solid #94a3b8', marginBottom: '5px' }}></div>
          <span style={{ fontSize: '11px', fontWeight: 'bold', color: '#475569' }}>Authorized Signatory</span>
        </div>
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '9px', color: '#64748b', borderTop: '1px solid #e2e8f0', paddingTop: '5px' }}>
        <div>
          AARYA INNOVTECH PVT. LTD. CIN: U29305MH2019PTC327551 | +91 8806796868<br/>
          Nashik Office: Flat No. 4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.
        </div>
        <div style={{ textAlign: 'right' }}>
          Generated by System
        </div>
      </div>
    </div>
  );

  return (
    <div className="print-template-wrapper print-only">
      <img src={logo} alt="Watermark" style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '500px', opacity: 0.06, zIndex: -1, pointerEvents: 'none' }} />
      
      {isTable ? (
        <table className="print-layout-table" style={{ width: '100%', borderCollapse: 'collapse', border: 'none' }}>
          <thead>
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <Header />
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <div className="print-body-content">
                  {children}
                </div>
              </td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td style={{ border: 'none', padding: 0 }}>
                <Footer />
              </td>
            </tr>
          </tfoot>
        </table>
      ) : (
        <div style={{ width: '100%' }}>
          <Header />
          <div className="print-body-content">
            {children}
          </div>
          <Footer />
        </div>
      )}
    </div>
  );
};

export default PrintTemplate;
